### ISSUE TITLE
How do i install Hebrew Elasticsearch plugin?

### ISSUE THREAD

**Issue by boriskezikov** [Sefaria/Sefaria-ElasticSearch#25]
Hi! Could you provide an instruction how can i install plugin into my elasticsearch? 
I am looking for a way to define hebrew-analyzer and work with it.

**Comment by nsantacruz** [comment]
Thank you for interest in this project! Please find instructions to install here: https://github.com/Sefaria/Sefaria-ElasticSearch/blob/master/README.md.
